# Generated by Django 4.0.4 on 2022-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dda_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackToint', models.IntegerField()),
                ('stationName', models.CharField(max_length=32)),
                ('parkingBikeToCnt', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('stationLatitude', models.FloatField()),
                ('stationLongitude', models.FloatField()),
                ('stationId', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'DDA_DB',
            },
        ),
    ]
